name: Release

on: 
  workflow_call: {}  

# permissions:
#   contents: write
#   pull-requests: write
#   security-events: write
#   actions: write
#   id-token: write
#   issues: write

permissions: write-all

jobs:
  publish-release:
    name: Execute Release Steps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .releaserc.yml
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: bjakym/gh-reusable-wf
          path: gh-reusable-wf
          ref: main
          sparse-checkout: |
            .releaserc.yml

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Files for both Repositories
        run: |
          ls -la

      # - name: Install Node.js 20.x
      #   run: |
      #     curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      #     sudo apt-get install -y nodejs
      #     node -v
      #     npm -v

      # - name: Publish Semantic Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure this token has write access to the repository
      #   run: |
      #     echo "Installing semantic release plug-ins ..."
      #     npm install @semantic-release/git @semantic-release/github @semantic-release/changelog @semantic-release/exec
      #     npm install --save @commitlint/cli @commitlint/config-conventional conventional-changelog-conventionalcommits conventional-changelog-eslint conventional-changelog-writer
      #     echo "Running semantic release ..."
      #     npx semantic-release --debug