name: 'PAFW Admin Reset'

on:
  workflow_call:
    inputs:
      runner_label:
        required: true
        type: string
      environment_name:
        required: true
        type: string
    secrets:
      VAULT_MOUNTPOINT_PA_FW_ADMIN:
        required: true
      VAULT_PATH_PA_FW_ADMIN:
        required: true
      VAULT_KEY_PA_FW_ADMIN_PASSWORD:
        required: true

defaults:
  run:
    shell: bash

permissions: write-all

jobs:
  execute_pafw_admin_reset:
    name: 'Execute Reset'
    environment: ${{ inputs.environment_name }}
    runs-on: ${{ inputs.runner_label }}

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Get vault token from jwt
      - name: Get Vault Token
        working-directory: .github/scripts
        id: vault
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          VAULT_NAMESPACE: ${{ vars.VAULT_LOCAL_NAMESPACE }}
          VAULT_ROLE: ${{ vars.VAULT_ROLE }}
        run: |
          chmod +x vault_token.sh
          ./vault_token.sh

      # Run the backup script (playbook)
      - name: Run Playbook
        id: run_playbook
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          VAULT_NAMESPACE: ${{ vars.VAULT_LOCAL_NAMESPACE }}
          VAULT_TOKEN: ${{ steps.vault.outputs.VAULT_TOKEN }}
        run: |
          python ansible-pa.py \
            -v projects/${{ inputs.environment_name }}/user-management/admin \
            -x '{"use_current_secret": true, "commit_changes": false, "vault_secret_path": "home_lab_admin"}' \
            -r plan \
            -f
