name: 'PAFW Admin Reset'

on:
  workflow_call:
    inputs:
      runner_label:
        required: true
        type: string
      environment_name:
        required: true
        type: string
      commit_changes:
        required: true
        type: boolean
        default: false
      use_current_secret:
        required: true
        type: boolean
        default: true
      config_folder:
        required: true
        type: string
      vault_namespace:
        required: true
        type: string
    secrets:
      VAULT_MOUNTPOINT_PA_FW_ADMIN:
        required: true
      VAULT_PATH_PA_FW_ADMIN:
        required: true
      VAULT_KEY_PA_FW_ADMIN_PASSWORD:
        required: true

defaults:
  run:
    shell: bash

permissions: write-all

jobs:
  execute_pafw_admin_reset:
    name: 'Execute'
    environment: ${{ inputs.environment_name }}
    runs-on: ${{ inputs.runner_label }}

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Vault Preparation
      - name: Prepare Vault
        id: vault_prep
        run: |
          # if vault_namespace is 'local', set VAULT_NAMESPACE to vars.VAULT_LOCAL_NAMESPACE
          if [ "${{ inputs.vault_namespace }}" == "local" ]; then
            echo "VAULT_NAMESPACE=${{ vars.VAULT_LOCAL_NAMESPACE }}" >> $GITHUB_OUTPUT
          fi
          # if vault_namespace is 'common', set VAULT_NAMESPACE to vars.VAULT_NAMESPACE
          if [ "${{ inputs.vault_namespace }}" == "common" ]; then
            echo "VAULT_NAMESPACE=${{ vars.VAULT_NAMESPACE }}" >> $GITHUB_OUTPUT
          fi
          # If VAULT_PATH_PA_FW_ADMIN contains */data in the beginning, remove it
          VAULT_PATH_PA_FW_ADMIN=$(echo "${{ secrets.VAULT_PATH_PA_FW_ADMIN }}" | sed 's/^.*\/data\///')
          echo "VAULT_PATH_PA_FW_ADMIN=${VAULT_PATH_PA_FW_ADMIN}" >> $GITHUB_OUTPUT
          # If VAULT_MOUNTPOINT_PA_FW_ADMIN contains */, remove everything after it
          VAULT_MOUNTPOINT_PA_FW_ADMIN=$(echo "${{ secrets.VAULT_MOUNTPOINT_PA_FW_ADMIN }}" | sed 's/\/.*//')
          echo "VAULT_MOUNTPOINT_PA_FW_ADMIN=${VAULT_MOUNTPOINT_PA_FW_ADMIN}" >> $GITHUB_OUTPUT

      # Get vault token from jwt
      - name: Get Vault Token
        working-directory: .github/scripts
        id: vault
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          VAULT_NAMESPACE: ${{ steps.vault_prep.outputs.VAULT_NAMESPACE }}
          VAULT_ROLE: ${{ vars.VAULT_ROLE }}
        run: |
          # Token file
          token_file="token.json"

          # Request the ID token
          curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | \
          jq "{ jwt: .value, role: \"$VAULT_ROLE\" }" > $token_file

          # Get the JWT token
          JWT_TOKEN=$(jq -r '.jwt' $token_file)

          # Authenticate using JWT_TOKEN to get VAULT_TOKEN
          export VAULT_TOKEN=$(
            curl -k -s --request POST \
            --header "X-Vault-Namespace: $VAULT_NAMESPACE" \
            --data "{\"jwt\":\"$JWT_TOKEN\",\"role\":\"$VAULT_ROLE\"}" \
            ${VAULT_ADDR}/v1/auth/jwt/login | jq -r '.auth.client_token'
          )

          echo "VAULT_TOKEN=${VAULT_TOKEN}" >> $GITHUB_OUTPUT

          # Clean up
          rm -f $token_file

          # Mask the token
          echo "::add-mask::$VAULT_TOKEN"

      # Run the backup script (playbook)
      - name: Run Playbook
        id: run_playbook
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          VAULT_NAMESPACE: ${{ steps.vault_prep.outputs.VAULT_NAMESPACE }}
          VAULT_TOKEN: ${{ steps.vault.outputs.VAULT_TOKEN }}
        run: |
          python ansible-pa.py \
            -v projects/${{ inputs.environment_name }}/${{ inputs.config_folder }} \
            -x '{
              "use_current_secret": ${{ inputs.use_current_secret }},
              "commit_changes": ${{ inputs.commit_changes }},
              "vault_engine_mount_point": "${{ steps.vault_prep.outputs.VAULT_MOUNTPOINT_PA_FW_ADMIN }}",
              "vault_secret_path": "${{ steps.vault_prep.outputs.VAULT_PATH_PA_FW_ADMIN }}",
              "vault_password_key": "${{ secrets.VAULT_KEY_PA_FW_ADMIN_PASSWORD }}"
            }' \
            -r apply \
            -i 1 \
            -f
